#!/bin/bash

cd ~/fox_12.1
	~/bin/repo sync
	cd ~/fox_12.1/bootable/recovery/
	git reset --hard origin/fox_12.1
	git pull
	git fetch https://gerrit.twrp.me/android_bootable_recovery refs/changes/93/5693/4 && git cherry-pick FETCH_HEAD
	git apply ~/5743.patch
	git apply ~/DST.patch
	git apply ~/settings.patch
	git apply ~/AVB20.patch
	cd ~/fox_12.1/vendor/recovery/
	git pull
