#!/bin/bash
cd ~/fox_12.1
	~/bin/repo sync
	cd ~/fox_12.1/system/vold/;
	git fetch https://gerrit.twrp.me/android_system_vold refs/changes/40/5540/11 && git cherry-pick FETCH_HEAD;
	cd ~/fox_12.1/bootable/recovery/
	git reset --hard origin/fox_12.1
	git pull --recurse-submodules
	git fetch https://gerrit.twrp.me/android_bootable_recovery refs/changes/39/5639/1 && git cherry-pick FETCH_HEAD;
	git fetch https://gerrit.twrp.me/android_bootable_recovery refs/changes/93/5693/4 && git cherry-pick FETCH_HEAD;
	cd ~/fox_12.1/vendor/recovery/
	git pull
	cd ~/fox_12.1/system/core/;
	git fetch https://gerrit.twrp.me/android_system_core refs/changes/75/5675/6 && git cherry-pick FETCH_HEAD;
